### ISSUE TITLE
blnet not working after update of Home Assistant Core to 2025.1.2

### ISSUE THREAD

**Issue by berndbru** [nielstron/ha_blnet#16]
I'm not so good in english language, but I try to discribe the problem:
after update Home Assistant Core to 2025.1.2 blnet not work.
The log says "... cannot import name 'TEMP_CELSIUS' from 'homeassistant.const ..."
I restore a backup with Home Assistant Core 2024.12.5 and blnet is working.

**Comment by nielstron** [comment]
Hi Bernd
Did you try updating to the latest version?
Should be fixed since 3c8088b55566468fa7a75e63515ba785555a42fd

**Comment by berndbru** [comment]
Hi Niels,
after installation of the new version via hacs the integration works generally after update of home assistant to 2025.1.2, but the sensors and swichtes are not recognized.
I make a few chances and found; when I change pyblnet in __init__.py and manifest.json back to 0.9.1 all worked.
With 0.9.2 and 0.9.3 no sensors and swichtes are recognized.

**Comment by MrPete2706** [comment]
Hi Niels,
after updating my HA-core to 2025.XX my BL-net integration stopped working.
Back to 2024.11 and everything worked fine again. I have been using your integration for years now withount any problems but now in 2025 I got stuck. Obviously the integration cannot read the blnet sensor-and switch entities any more.
Have I missed something?

**Comment by nielstron** [comment]
@berndbru which changes exactly did you make to `__init__.py` and `manifest.json`? Did you change the entire content of them back to the state of 0.9.1 while keeping the remainder at the status of 0.9.3?

**Comment by nielstron** [comment]
The main change between 0.9.1 and 0.9.3 I see could be https://github.com/nielstron/pyblnet/pull/38 - changing the website where the request to change the node is sent.

Either this is the error, or the lack of unique names, which has been resolved in the latest fix #19 

Can you please check if the latest version of the component already resolves this issue?

**Comment by berndbru** [comment]
I install today the latest version of blnet-integration and all is working fine without changes in the files __init__.py or manifest.json.

**Comment by nielstron** [comment]
Great, thanks for letting me know!

**Comment by berndbru** [comment]
In fact, after updating the integration to the latest version, the integration only worked properly again after I set the entries for pyblnet in the __init__.py and manifest.json files back to 0.9.1.
Sorry for the false information from 2 hours ago.

**Comment by berndbru** [comment]
The error in the log in case pyblnet is set to 0.9.2:
Logger: homeassistant.setup
Quelle: setup.py:422
Erstmals aufgetreten: 15:11:51 (1 Vorkommnisse)
Zuletzt protokolliert: 15:11:51

Error during setup of component blnet: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 422, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/blnet/__init__.py", line 102, in setup
    update_handler.schedule_updates()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/blnet/__init__.py", line 311, in schedule_updates
    fetch_data()
    ~~~~~~~~~~^^
  File "/config/custom_components/blnet/__init__.py", line 308, in fetch_data
    return self.data_handler.update()
           ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/config/custom_components/blnet/__init__.py", line 189, in update
    data = self._fetch_data()
  File "/config/custom_components/blnet/__init__.py", line 196, in _fetch_data
    return self.blnet.fetch(self.node)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyblnet/blnet.py", line 90, in fetch
    data["digital"] = self._convert_web(blnet_session.read_digital_values())
                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/pyblnet/blnet_web.py", line 246, in read_digital_values
    data_raw = dom.text()
               ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by nielstron** [comment]
Hi @MrPete2706 ,

Thank you for reporting. Can you please try the following and report the results:

Manually log in to your BLNET using the webbrowser. For each page, report which website it maps to. Note the main URL does not change but you can right-click on the changed frame to "open frame in new tab" and then see the URL of the frame. Alternatively open the "Network Monitor" while navigating through the website. For example, when reading the analog values, it should be `<blnet ip>/580500.htm`. For changing the CAN node it should be `<blnet ip>/can.htm?blaB=<node>`.

Specifically, please navigate to 1) change the node and to read 2) analog and 3) digital values and report the URLs. Thank you!

**Comment by nielstron** [comment]
I also meant to tag @berndbru , sorry for the confusion!
